[Major] Require samples for all operations
zapier/zapier-platform-schema pull request #32
Opened 2018-02-16 20:26 UTC by ibolmo

This will require a bump in major. We will now require samples from all (trigger, creates, and search) operations.

We'll need to coordinate the release to NPM, and other repos.

2018-02-17 01:04 UTC, xavdid requested changes
Everything looks good, just need to revert the manual version change. @eliangcs on monday you can merge this and major. We can also do it on (our) tuesday if we need to check anything else.

2018-02-17 01:04 UTC, xavdid commented on package.json
> +  "version": "5.0.0",
don't change this manually, we set it during the deploy process.

2018-02-19 08:01 UTC, eliangcs approved these changes
👍 Good to merge once we revoke the version bump in `package.json`.

2018-02-19 17:44 UTC, ibolmo commented
@xavdid went ahead and dropped that commit (-f pushed to this branch). 

Thanks!

2018-02-19 19:15 UTC, xavdid approved these changes

2018-02-19 20:57 UTC, merged

2018-02-21 19:50 UTC, codebycaleb commented
A user from the zapier-platform slack brought up an issue with these changes. To be brief, the user pointed out that with the changes to `BasicPollingOperationSchema`, any `ResourceSchema`'s `list.operation` (which is a `BasicPollingOperationSchema`) will also require the `sample` field. The specific example they provided was with regards to defining a dynamic drop down field. The `sample` provided wouldn't necessarily be helpful to be used.

2018-02-23 00:47 UTC, b4Beta commented
Since upgrading to 5.0.0, `zapier push` fails, but `zapier validate` does not
https://cbo.d.pr/fy060g

2018-02-23 01:05 UTC, xavdid commented
@b4Beta Can you run `zapier validate --debug` and see if the output is different?

2018-02-23 01:33 UTC, b4Beta commented
It was not different apart from the more verbose output

```
Preparing to build and upload your app.

  Copying project to temp directory     done!
  Installing project dependencies     done!
  Applying entry point file     done!
  Building app definition.json     done!
  Validating project ..

Error! We hit some validation errors, try running `zapier validate` to see them!
(Use --debug flag and run this command again to get more details.)

C:\Users\Zapier\Documents\path\to\file>zapier validate --debug

Validating project locally.
No structural errors found during validation routine.
This project is structurally sound!

Checking app style.
>> POST https://zapier.com/api/platform/cli/style-check
>> ....{{App specific stuff}}...
<< 200
<< {"errors": {}, "warnings": {}}

No style errors found during validation routine.
Your app looks great!
```

2018-02-23 01:34 UTC, xavdid commented
weird. can you build verbose? It seems like the error is happening and mistakenly being called a validation error

2018-02-23 01:37 UTC, b4Beta commented
```
  Applying entry point file     done!
  Building app definition.json     done!
  Validating project
Error: We hit some validation errors, try running `zapier validate` to see them!
    at C:\Program Files (x86)\Nodist\bin\node_modules\zapier-platform-cli\lib\utils\build.js:314:13

Error!```

2018-02-23 01:43 UTC, xavdid commented
Very strange. I'm going to file a separate issue and tag you and we can go from there.

2018-02-23 01:46 UTC, b4Beta commented
I updated my comment with more details.

2018-02-23 01:49 UTC, xavdid commented
Ah! This is less mysterious than I thought. Definitely a bug though. 

The short answer is yes, each of those needs a sample. The good news is that you can put a single sample at the top of the file and use it in each of the `[get|list|search|create]` methods.

2018-02-23 01:53 UTC, b4Beta commented
Mmmm...That is quite a bit of work and not the documented way
https://github.com/zapier/zapier-platform-example-app-resource/blob/master/resources/recipe.js

Shows `module.exports` with one `sample` as the second last property of the object - that is how I have implemented it.

2018-02-23 01:59 UTC, xavdid commented
Ah, sorry about that. It's a recent change and we're still in the process of updating documentation. If you've already written the sample, it should be an easy fix!

Instead of 
```js
module.exports = {
  key: 'recipe',
  noun: 'Recipe',

  get: {
    display: {
      label: 'Get Recipe',
      description: 'Gets a recipe.',
    },
    operation: {
      inputFields: [
        { key: 'id', required: true },
      ],
      perform: () => { },
    },
  },

  sample: {
    id: 1,
    createdAt: 1472069465,
    name: 'Best Spagetti Ever',
    authorId: 1,
    directions: '1. Boil Noodles\n2.Serve with sauce',
    style: 'italian',
  },

  outputFields: [
    { key: 'id', label: 'ID' },
    { key: 'createdAt', label: 'Created At' },
    { key: 'name', label: 'Name' },
    { key: 'directions', label: 'Directions' },
    { key: 'authorId', label: 'Author ID' },
    { key: 'style', label: 'Style' },
  ]
};
```

change it to

```js
const sample = {
  id: 1,
  createdAt: 1472069465,
  name: 'Best Spagetti Ever',
  authorId: 1,
  directions: '1. Boil Noodles\n2.Serve with sauce',
  style: 'italian',
}

module.exports = {
  key: 'recipe',
  noun: 'Recipe',

  get: {
    display: {
      label: 'Get Recipe',
      description: 'Gets a recipe.',
    },
    operation: {
      inputFields: [
        { key: 'id', required: true },
      ],
      perform: () => { },
      sample: sample // ADD THIS LINE
    },
  },

  sample: sample,

  outputFields: [
    { key: 'id', label: 'ID' },
    { key: 'createdAt', label: 'Created At' },
    { key: 'name', label: 'Name' },
    { key: 'directions', label: 'Directions' },
    { key: 'authorId', label: 'Author ID' },
    { key: 'style', label: 'Style' },
  ]
};
```

If you don't want to do this, you're also free to continue using v4 for now. This is totally a pain point though, so we'll see what we can do about that.

2018-03-01 00:12 UTC, b4Beta commented
Just to let you know that the `scaffold` for `resource` has not been updated.

2018-03-01 01:35 UTC, xavdid commented
@b4Beta It's on my list to fix this week!

In the meantime, do you mind popping over to zapier/zapier-platform-cli#250 and posting a code example to help me reproduce the issue where `build` reports errors, but `validate` doesn't? I used both the resource scaffold and made a new app with the resource template and both failed `validate` correctly.